cd music_enc\\win32
for /f "tokens=1 delims= " %%a in ('dir /b') do set packname=%%a

cd %packname%\win32
del d3dcompiler_47.dll
del nw_200_percent.pak
del libEGL.dll
del libGLESv2.dll
rd /s /q swiftshader

cd locales
del am.pak
del am.pak.info
del ar.pak
del ar.pak.info
del bg.pak
del bg.pak.info
del bn.pak
del bn.pak.info
del ca.pak
del ca.pak.info
del cs.pak
del cs.pak.info
del da.pak
del da.pak.info
del de.pak
del de.pak.info
del el.pak
del el.pak.info
del en-GB.pak
del en-GB.pak.info
del en-US.pak
del en-US.pak.info
del es-419.pak
del es-419.pak.info
del es.pak
del es.pak.info
del et.pak
del et.pak.info
del fa.pak
del fa.pak.info
del fi.pak
del fi.pak.info
del fil.pak
del fil.pak.info
del fr.pak
del fr.pak.info
del gu.pak
del gu.pak.info
del he.pak
del he.pak.info
del hi.pak
del hi.pak.info
del hr.pak
del hr.pak.info
del hu.pak
del hu.pak.info
del id.pak
del id.pak.info
del it.pak
del it.pak.info
del kn.pak
del kn.pak.info
del ko.pak
del ko.pak.info
del lt.pak
del lt.pak.info
del lv.pak
del lv.pak.info
del ml.pak
del ml.pak.info
del mr.pak
del mr.pak.info
del ms.pak
del ms.pak.info
del nb.pak
del nb.pak.info
del nl.pak
del nl.pak.info
del pl.pak
del pl.pak.info
del pt-BR.pak
del pt-BR.pak.info
del pt-PT.pak
del pt-PT.pak.info
del ro.pak
del ro.pak.info
del ru.pak
del ru.pak.info
del sk.pak
del sk.pak.info
del sl.pak
del sl.pak.info
del sr.pak
del sr.pak.info
del sv.pak
del sv.pak.info
del sw.pak
del sw.pak.info
del ta.pak
del ta.pak.info
del te.pak
del te.pak.info
del th.pak
del th.pak.info
del tr.pak
del tr.pak.info
del uk.pak
del uk.pak.info
del vi.pak
del vi.pak.info
del zh-CN.pak
del zh-CN.pak.info
del zh-TW.pak
del zh-TW.pak.info
